export const DASHBOARD_URL = "/"
export const CUSTOMERS_URL = "/customers/"
export const CUSTOMER_DETAIL_URL = "/customers/:customer_id"
export const PRODUCTS_URL = "/products/"
export const CATEGORIES_URL = "/categories/"
